[package]
name = "square_wheel"
version = "0.1.0"
authors = ["Panzerschrek <AntiPanzerschrek@yandex.ru>"]
edition = "2018"

[profile.release]
panic = "abort"
lto = true

[features]
rasterizer_unchecked_div = []

[dependencies]
cgmath = "0.18"
sdl2 = { version = "0.35", features = ["image"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"

# Library with common code.
[lib]
name = "common"
path = "common/lib.rs"

# Map compiler executable.
[[bin]]
name = "map_compiler"
path = "map_compiler/main.rs"


# Lightmapper executable.
[[bin]]
name = "lightmapper"
path = "lightmapper/main.rs"


# Vis executable.
[[bin]]
name = "vis"
path = "vis/main.rs"


# Helper tool for map visualisation.
[[bin]]
name = "map_viewer"
path = "map_viewer/main.rs"

# Engine itself.
[[bin]]
name = "square_wheel"
path = "square_wheel/main.rs"
