[package]
name = "src"
version = "0.1.0"
authors = ["Panzerschrek <AntiPanzerschrek@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18"
structopt = "0.3"

[[bin]]
name = "map_compiler"
path = "map_compiler/main.rs"
