edition = "2018"
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
comment_width = 120
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
fn_args_layout = "Tall"
fn_single_line = false
format_strings = true
hard_tabs = true
imports_granularity = "Crate"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
