on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # Clone repository and submodules
    - name: Fetch
      uses: actions/checkout@v2
      with:
        submodules: recursive
    # Install Rust compiler
    - name: Rustup
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: default
        toolchain: 1.60.0
    # Install non-Rust dependencies
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev
    # Build debug
    - name: BuildDebug
      working-directory: src
      run: cargo build
    # Build release
    - name: BuildRelease
      working-directory: src
      run: ./build_release.sh
    # Check formatting in parallel, using nightly toolchain.
  check_fmt:
      runs-on: ubuntu-20.04
      steps:
      - name: Fetch
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Rustup
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: default
          toolchain: nightly
      - name: Check rustfmt
        working-directory: src
        run: cargo fmt -- --check
